// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8oT1PsVnWD8I3fm2b8ifj_kiUD84y7B0',
    appId: '1:149210235880:web:dff6876fc0f57f57629a5d',
    messagingSenderId: '149210235880',
    projectId: 'login-5f211',
    authDomain: 'login-5f211.firebaseapp.com',
    storageBucket: 'login-5f211.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO2avuXmsBcRT9ClkO2HUSQpOYRQry8yc',
    appId: '1:149210235880:android:9c75f04c59ec60a2629a5d',
    messagingSenderId: '149210235880',
    projectId: 'login-5f211',
    storageBucket: 'login-5f211.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ_qyzrcgtDfTH8me0_mLnQBqNpwaflqM',
    appId: '1:149210235880:ios:9c343b0f5980b790629a5d',
    messagingSenderId: '149210235880',
    projectId: 'login-5f211',
    storageBucket: 'login-5f211.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ_qyzrcgtDfTH8me0_mLnQBqNpwaflqM',
    appId: '1:149210235880:ios:9c343b0f5980b790629a5d',
    messagingSenderId: '149210235880',
    projectId: 'login-5f211',
    storageBucket: 'login-5f211.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8oT1PsVnWD8I3fm2b8ifj_kiUD84y7B0',
    appId: '1:149210235880:web:84221689383c97f3629a5d',
    messagingSenderId: '149210235880',
    projectId: 'login-5f211',
    authDomain: 'login-5f211.firebaseapp.com',
    storageBucket: 'login-5f211.appspot.com',
  );
}
